name: "01 - simple exemple"

on: push

jobs:
  afficher-info:
    runs-on: ubuntu-latest
    steps: 
      - name: "afficher des infos"
        run: |
          echo "Push detecte"
          echo "Author : ${{ github.actor }}"
          echo "branch : ${{ github.ref_name }}"
          echo "sha : ${{ github.sha }}"